dist: trusty
sudo: required
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y make g++-4.9 libboost-dev libgmp-dev flexc++ bisonc++
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - pip install --user cpp-coveralls
script: ./bootstrap && make coverage
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
